Change Sum class's constructor stores for each parameter to its member variables(augend, addend) to fix following JUnit test testPlusReturnsSum fail
> Task :test FAILED

Cannot read field "amount" because "money" is null
java.lang.NullPointerException: Cannot read field "amount" because "money" is null
	at Money.equals(Money.java:28)
	at org.junit.jupiter.api.AssertionUtils.objectsAreEqual(AssertionUtils.java:110)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)
	at MainTests.testPlusReturnsSum(mainTest.java:40)