Add Dollar class constructor to fix build error
error: constructor Dollar in class Dollar cannot be applied to given types;
        Dollar five = new Dollar(5);
                      ^
  required: no arguments
  found:    int
  reason: actual and formal argument lists differ in length