Add condition check to Bank class's rate member method that returns 1 when from and to currency is same
> Task :test FAILED

Cannot invoke "java.lang.Integer.intValue()" because "rate" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "rate" is null
	at Bank.rate(Bank.java:12)
	at Money.reduce(Money.java:41)
	at Bank.reduce(Bank.java:7)
	at MainTests.testReduceMoney(mainTest.java:55)

Cannot invoke "java.lang.Integer.intValue()" because "rate" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "rate" is null
	at Bank.rate(Bank.java:12)
	at MainTests.testIdentityRate(mainTest.java:69)