Change Sum class's plus member method to fix following JUnit test testSumPlusMoney fail
> Task :test FAILED

Cannot invoke "Expression.reduce(Bank, String)" because "source" is null
java.lang.NullPointerException: Cannot invoke "Expression.reduce(Bank, String)" because "source" is null
	at Bank.reduce(Bank.java:7)
	at MainTests.testSumPlusMoney(mainTest.java:90)