Change Bank class's reduce member method to return assert pass fake implementation to fix the following JUnit test testSimpleAddition fail
> Task :test FAILED

Cannot read field "amount" because "money" is null
java.lang.NullPointerException: Cannot read field "amount" because "money" is null
	at Money.equals(Money.java:28)
	at org.junit.jupiter.api.AssertionUtils.objectsAreEqual(AssertionUtils.java:110)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)